#!/usr/bin/env python3
"""
build.py — schema.dbml → assets/schema.js + tables/<name>.html

Reads a single DBML file (the source of truth) and regenerates:
  - assets/schema.js          # window.SCHEMA = { ... }
  - tables/<table>.html       # one stub per table, cloned from _table.html

Run from the output directory:
  $ pip install -r requirements.txt
  $ python build.py
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

try:
    from pydbml import PyDBML
except ImportError:
    sys.stderr.write(
        "ERROR: pydbml not installed. Run: pip install -r requirements.txt\n"
    )
    sys.exit(2)


# ── pydbml → dict conversion ────────────────────────────────────────────────

def _note_text(note_obj) -> str:
    """pydbml Note may be None, a Note object, or a plain string."""
    if note_obj is None:
        return ""
    text = getattr(note_obj, "text", None)
    return text if isinstance(text, str) else str(note_obj)


def _stringify_default(default):
    """pydbml default may be str, Expression, or None."""
    if default is None:
        return None
    return str(default)


def _column_to_dict(col, fk_map):
    table_name = getattr(col.table, "name", None)
    name = col.name
    type_str = str(col.type) if col.type is not None else ""
    pk = bool(getattr(col, "pk", False))
    uk = bool(getattr(col, "unique", False))
    not_null = bool(getattr(col, "not_null", False))
    nullable = not (pk or not_null)
    out = {
        "name": name,
        "type": type_str,
        "pk": pk,
        "uk": uk,
        "nullable": nullable,
        "default": _stringify_default(getattr(col, "default", None)),
        "comment": _note_text(getattr(col, "note", None)),
    }
    fk = fk_map.get((table_name, name))
    if fk:
        out["fk"] = fk
    return out


def _index_to_dict(ix):
    subjects = []
    for s in getattr(ix, "subjects", []) or []:
        # subject can be a Column, a string (expression), or have a .name
        n = getattr(s, "name", None)
        subjects.append(n if isinstance(n, str) else str(s))
    return {
        "name": getattr(ix, "name", "") or "",
        "columns": subjects,
        "unique": bool(getattr(ix, "unique", False)),
    }


def _resolve_refs(parsed):
    """Build (origin_table, origin_col) -> {table, column} fk map plus relations list.

    DBML ref types:
      '>'  many-to-one    : col1 references col2
      '<'  one-to-many    : col2 references col1 (swap origin/target)
      '-'  one-to-one     : treat col1 as origin
      '<>' many-to-many   : materialize as col1→col2 (rare; informational only)
    """
    fk_map = {}
    relations = []
    for ref in getattr(parsed, "refs", []) or []:
        rtype = getattr(ref, "type", ">")
        if rtype == "<":
            origins, targets = ref.col2, ref.col1
        else:
            origins, targets = ref.col1, ref.col2
        if not isinstance(origins, (list, tuple)):
            origins = [origins]
        if not isinstance(targets, (list, tuple)):
            targets = [targets]
        for origin, target in zip(origins, targets):
            origin_table = getattr(origin.table, "name", None)
            target_table = getattr(target.table, "name", None)
            if origin_table is None or target_table is None:
                continue
            fk_map[(origin_table, origin.name)] = {
                "table": target_table,
                "column": target.name,
            }
            relations.append({
                "from": origin_table,
                "from_col": origin.name,
                "to": target_table,
                "to_col": target.name,
            })
    return fk_map, relations


def build_schema_object(parsed, dbml_text):
    fk_map, relations = _resolve_refs(parsed)

    tables = []
    for tbl in parsed.tables:
        tables.append({
            "name": tbl.name,
            "comment": _note_text(getattr(tbl, "note", None)),
            "columns": [_column_to_dict(c, fk_map) for c in tbl.columns],
            "indexes": [_index_to_dict(ix) for ix in (getattr(tbl, "indexes", []) or [])],
        })

    enums = []
    for en in getattr(parsed, "enums", []) or []:
        values = []
        for item in getattr(en, "items", []) or []:
            n = getattr(item, "name", None)
            values.append(n if isinstance(n, str) else str(item))
        enums.append({"name": en.name, "values": values})

    return {
        "source_dbml": dbml_text,
        "tables": tables,
        "relations": relations,
        "enums": enums,
    }


# ── rendering ───────────────────────────────────────────────────────────────

def render_schema_js(schema_obj):
    payload = json.dumps(schema_obj, ensure_ascii=False, indent=2)
    return f"// Generated by build.py — do not edit by hand.\nwindow.SCHEMA = {payload};\n"


_SAFE_NAME = re.compile(r"[^A-Za-z0-9_.\-]")


def safe_filename(name):
    return _SAFE_NAME.sub("_", name)


def render_table_page(template_html, table_name):
    return template_html.replace("__TABLE_NAME__", table_name)


# ── error reporting ─────────────────────────────────────────────────────────

def _print_parse_error(dbml_text, exc, src_path):
    """pydbml ParseException → line:col + ±3 context + likely causes."""
    lines = dbml_text.splitlines()
    lineno = getattr(exc, "lineno", None) or getattr(exc, "line", None)
    col = getattr(exc, "col", None) or getattr(exc, "column", None)

    sys.stderr.write(f"\nDBML 파싱 실패: {src_path}\n")
    if lineno:
        loc = f"line {lineno}"
        if col:
            loc += f" col {col}"
        sys.stderr.write(f"  위치: {loc}\n")
    sys.stderr.write(f"  메시지: {exc}\n")

    if isinstance(lineno, int) and 1 <= lineno <= len(lines):
        sys.stderr.write("\n--- 주변 컨텍스트 ---\n")
        start = max(1, lineno - 3)
        end = min(len(lines), lineno + 3)
        for i in range(start, end + 1):
            marker = ">>" if i == lineno else "  "
            sys.stderr.write(f"{marker} {i:5d} | {lines[i - 1]}\n")

    sys.stderr.write(
        "\n흔한 원인 (pydbml 실측):\n"
        "  1. 식별자/타입을 backtick(`)으로 감쌌나요? pydbml은 backtick을 받지 않습니다.\n"
        "     → 식별자·타입은 plain 또는 \"...\" (double-quote) 만.\n"
        "  2. 한글 등 비-ASCII가 들어간 타입(예: enum('A','일치'))이 plain인가요?\n"
        "     → 타입 전체를 \"...\"로 감싸세요. 예: \"enum('A','일치')\"\n"
        "  3. DBML 예약어와 같은 컬럼명(default, type, table, ref, indexes, DECISION 등)?\n"
        "     → 컬럼명을 \"...\"로 감싸세요.\n"
        "  4. 숫자로 시작하는 식별자(2023_export, 3UCL)?\n"
        "     → \"...\"로 감싸세요.\n"
        "  자세한 규칙은 SKILL.md의 'pydbml Quoting Rules' 참고.\n"
    )


# ── main ────────────────────────────────────────────────────────────────────

def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--in",  dest="inp", default="schema.dbml",
                   help="Input DBML file (default: schema.dbml)")
    p.add_argument("--out", dest="out", default=".",
                   help="Output directory (default: current directory)")
    args = p.parse_args()

    in_path = Path(args.inp)
    out_dir = Path(args.out)

    if not in_path.exists():
        sys.stderr.write(f"ERROR: {in_path} not found.\n")
        sys.exit(1)

    dbml_text = in_path.read_text(encoding="utf-8")
    try:
        parsed = PyDBML(dbml_text)
    except Exception as e:
        _print_parse_error(dbml_text, e, in_path)
        sys.exit(2)
    schema_obj = build_schema_object(parsed, dbml_text)

    # Write assets/schema.js
    assets_dir = out_dir / "assets"
    assets_dir.mkdir(parents=True, exist_ok=True)
    (assets_dir / "schema.js").write_text(
        render_schema_js(schema_obj), encoding="utf-8"
    )

    # Stamp tables/<name>.html from _table.html
    tables_dir = out_dir / "tables"
    tables_dir.mkdir(parents=True, exist_ok=True)
    template_path = tables_dir / "_table.html"
    if not template_path.exists():
        sys.stderr.write(
            f"ERROR: {template_path} not found. "
            f"Make sure templates/ was copied to {out_dir}.\n"
        )
        sys.exit(1)
    tpl = template_path.read_text(encoding="utf-8")

    # Sweep old generated table pages (keep _table.html and index.html)
    keep = {"_table.html", "index.html"}
    for existing in tables_dir.glob("*.html"):
        if existing.name not in keep:
            existing.unlink()

    for tbl in schema_obj["tables"]:
        fname = safe_filename(tbl["name"]) + ".html"
        (tables_dir / fname).write_text(
            render_table_page(tpl, tbl["name"]),
            encoding="utf-8"
        )

    n_tables = len(schema_obj["tables"])
    n_rels = len(schema_obj["relations"])
    n_idx = sum(len(t["indexes"]) for t in schema_obj["tables"])
    print(f"build complete — {n_tables} tables, {n_rels} relations, {n_idx} indexes")
    print(f"  -> {assets_dir / 'schema.js'}")
    print(f"  -> {tables_dir}/ ({n_tables} html files)")


if __name__ == "__main__":
    main()
